// <auto-generated />
namespace RestPOC.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ApiKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApiKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201212212051129_ApiKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
